{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
spec:
  type: Opaque
  data:
    tls.crt: {{ .Files.Get .Values.tls.CertPath | b64enc }}
    tls.key: {{ .Files.Get .Values.tls.KeyPath | b64enc }}
{{- end }}